/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Odmaa;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import power.wise.app.PowerWiseGUI;

/**
 *
 * @author apple
 */
public class AddApplianceForm extends javax.swing.JFrame {
    private ArrayList<Appliance> appliance;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddApplianceForm.class.getName());
    String applianceName;
    double energyUsage, wattage, hours;
    /**
     * Creates new form AddApplianceForm
     */
    public AddApplianceForm() {
        appliance = new ArrayList<>();
        initComponents();
    }
    /**
     * Constructor used from ApplianceListForm, with name prefilled
    */
    public AddApplianceForm(String selectedName) {
        initComponents();
        setupCommonUi(true);  // lock name
        nameTF.setText(selectedName);
    }
    
    private void setupCommonUi(boolean lockName) {
        // numeric-only for wattage and hours
        wattageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });

        hoursTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });

        // name behaviour
        nameTF.setEditable(!lockName);

        // message box behaviour
        displayTA.setEditable(false);
        displayTA.setLineWrap(true);
        displayTA.setWrapStyleWord(true);
        displayTA.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        mainPL = new javax.swing.JPanel();
        saveBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        hoursLBL = new javax.swing.JLabel();
        wattageTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        wattageLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPL.setBackground(new java.awt.Color(26, 101, 26));

        titleLBL.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Power Wise - Add Appliance Form");

        javax.swing.GroupLayout headerPLLayout = new javax.swing.GroupLayout(headerPL);
        headerPL.setLayout(headerPLLayout);
        headerPLLayout.setHorizontalGroup(
            headerPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPLLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPLLayout.setVerticalGroup(
            headerPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLBL)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainPL.setBackground(new java.awt.Color(204, 255, 204));
        mainPL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });
        mainPL.add(saveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        mainPL.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        hoursLBL.setText("Hours Used By Day:");
        mainPL.add(hoursLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        mainPL.add(wattageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, -1));
        mainPL.add(hoursTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 120, 240, -1));
        mainPL.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 240, -1));

        nameLBL.setText("Name:");
        mainPL.add(nameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        wattageLBL.setText("Wattage:");
        mainPL.add(wattageLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        mainPL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPL, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(headerPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        new PowerWiseGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        try {
            String name = nameTF.getText().trim();
            String wattStr = wattageTF.getText().trim();
            String hrsStr = hoursTF.getText().trim();

            // validation
            if (name.isEmpty()) {
                displayTA.setText("Appliance name missing.");
                return;
            }

            if (wattStr.isEmpty() || hrsStr.isEmpty()) {
                displayTA.setText("Please enter wattage and hours.");
                return;
            }

            double watt = Double.parseDouble(wattStr);
            double hrs = Double.parseDouble(hrsStr);
            double energy = watt * hrs;

            // ensure data folder exists
            File folder = new File("data");
            if (!folder.exists()) {
                folder.mkdir();
            }

            File f = new File(folder, "applianceList.txt");

            // read existing content and remove old block for this appliance
            StringBuilder newFile = new StringBuilder();
            if (f.exists()) {
                try (BufferedReader br = new BufferedReader(new FileReader(f))) {
                    String line;
                    boolean skip = false;

                    while ((line = br.readLine()) != null) {

                        if (line.startsWith("Appliance Name: ")) {
                            String existingName =
                                    line.substring("Appliance Name: ".length()).trim();
                            // if same appliance, skip its old block
                            skip = existingName.equalsIgnoreCase(name);
                        }

                        if (!skip) {
                            newFile.append(line).append("\n");
                        }

                        // end of block = blank line
                        if (line.trim().isEmpty()) {
                            skip = false;
                        }
                    }
                }
            }

            // append new clean block
            newFile.append("Appliance Name: ").append(name).append("\n");
            newFile.append("Wattage: ").append(watt).append("\n");
            newFile.append("Hours of Usage: ").append(hrs).append("\n");
            newFile.append("Energy Usage: ").append(energy).append("\n\n");

            // write back
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(f))) {
                bw.write(newFile.toString());
            }

            displayTA.setText(
                "Saved!\n\n" +
                name + " updated in your appliance list.\n" +
                "Go to Reports to generate your report."
            );
            displayTA.setCaretPosition(0);

        } catch (Exception e) {
            displayTA.setText("Error saving appliance. Please check your inputs.");
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddApplianceForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JPanel headerPL;
    private javax.swing.JLabel hoursLBL;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPL;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel wattageLBL;
    private javax.swing.JTextField wattageTF;
    // End of variables declaration//GEN-END:variables
}
