/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Odmaa;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author apple
 */
public class ApplianceListForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ApplianceListForm.class.getName());
  
    
    /**
     * Creates new form ApplianceListForm
     */
    public ApplianceListForm() {
        initComponents();
        loadComboBox();

        // Make the display area read-only and nice to read
        displayTA.setEditable(false);
        displayTA.setLineWrap(true);
        displayTA.setWrapStyleWord(true);
        displayTA.setFocusable(false);
    }
    // Load list of appliance types
    private void loadComboBox() {
        searchappliance.removeAllItems();
        searchappliance.addItem("Choose Appliance");
        searchappliance.addItem("Laptop");
        searchappliance.addItem("Heater");
        searchappliance.addItem("Fridge");
        searchappliance.addItem("TV");
        searchappliance.addItem("Washing Machine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        applianceLBL = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        iconLBL = new javax.swing.JLabel();
        backLBL = new javax.swing.JLabel();
        removeBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        backgroundPL = new javax.swing.JPanel();
        searchBTN = new javax.swing.JButton();
        searchappliance = new javax.swing.JComboBox<>();
        backgroundLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(26, 101, 26));

        applianceLBL.setBackground(new java.awt.Color(26, 101, 26));
        applianceLBL.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        applianceLBL.setForeground(new java.awt.Color(255, 255, 255));
        applianceLBL.setText("Power Wise - Appliance List Form");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(applianceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(applianceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.setToolTipText("");
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBTN.setBackground(new java.awt.Color(26, 101, 26));
        backBTN.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        mainPanel.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, 40));

        addBTN.setBackground(new java.awt.Color(26, 101, 26));
        addBTN.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        addBTN.setForeground(new java.awt.Color(255, 255, 255));
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        mainPanel.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, 40));

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/electric-appliance.png"))); // NOI18N
        iconLBL.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mainPanel.add(iconLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 20, 110, 120));

        backLBL.setBackground(new java.awt.Color(153, 255, 255));
        mainPanel.add(backLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 320, 30));

        removeBTN.setBackground(new java.awt.Color(26, 101, 26));
        removeBTN.setForeground(new java.awt.Color(255, 255, 255));
        removeBTN.setText("REMOVE");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });
        mainPanel.add(removeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 40));

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        backgroundPL.setBackground(new java.awt.Color(26, 101, 26));
        backgroundPL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchBTN.setForeground(new java.awt.Color(26, 101, 26));
        searchBTN.setText("SEARCH");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        searchappliance.setForeground(new java.awt.Color(26, 101, 26));
        searchappliance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Appliance" }));
        searchappliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchapplianceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPLLayout = new javax.swing.GroupLayout(backgroundPL);
        backgroundPL.setLayout(backgroundPLLayout);
        backgroundPLLayout.setHorizontalGroup(
            backgroundPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPLLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(searchappliance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgroundPLLayout.setVerticalGroup(
            backgroundPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(searchappliance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(backgroundPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 390, 60));

        backgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/appliancebackground.jpg"))); // NOI18N
        backgroundLBL.setText("cb");
        mainPanel.add(backgroundLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 900, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
                
    
    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        new ApplianceGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String selectedName = searchappliance.getSelectedItem().toString();

        if (selectedName.equals("Choose Appliance")) {
            JOptionPane.showMessageDialog(this, "Please select an appliance type.");
            return;
        }

        new AddApplianceForm(selectedName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addBTNActionPerformed
    
    private void searchapplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchapplianceActionPerformed
        // TODO add your handling code here:
           
        
    }//GEN-LAST:event_searchapplianceActionPerformed
    
    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        String selectedName = searchappliance.getSelectedItem().toString();

        if (selectedName.equals("Choose Appliance")) {
            displayTA.setText("Please select an appliance first.");
            return;
        }

        File folder = new File("data");
        File f = new File(folder, "applianceList.txt");

        if (!f.exists()) {
            displayTA.setText("No appliance data found.\nPlease add appliances in the Energy Usage section.");
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(f))) {

            String line;
            boolean found = false;

            String name = "", watt = "", hrs = "", energy = "";

            while ((line = br.readLine()) != null) {

                if (line.startsWith("Appliance Name: ")) {

                    name = line.substring("Appliance Name: ".length()).trim();

                    if (name.equalsIgnoreCase(selectedName)) {

                        String lineWatt = br.readLine();
                        String lineHrs = br.readLine();
                        String lineEnergy = br.readLine();

                        if (lineWatt != null && lineWatt.startsWith("Wattage: ")) {
                            watt = lineWatt.substring("Wattage: ".length()).trim();
                        }

                        if (lineHrs != null && lineHrs.startsWith("Hours of Usage: ")) {
                            hrs = lineHrs.substring("Hours of Usage: ".length()).trim();
                        }

                        if (lineEnergy != null && lineEnergy.startsWith("Energy Usage: ")) {
                            energy = lineEnergy.substring("Energy Usage: ".length()).trim();
                        }

                        found = true;
                        break;
                    }
                }
            }

            if (found) {
                displayTA.setText(
                    "Appliance Name: " + name + "\n" +
                    "Wattage: " + watt + " W\n" +
                    "Hours Used: " + hrs + " hrs/day\n" +
                    "Energy Usage: " + energy + " Wh/day"
                );
                displayTA.setCaretPosition(0);
            } else {
                displayTA.setText("No appliance data found for " + selectedName +
                                  ".\nPlease add it in the Energy Usage section.");
            }

        } catch (IOException e) {
            displayTA.setText("Error reading appliance data.");
            System.out.println("Error: " + e);
        }
        
    }//GEN-LAST:event_searchBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        // TODO add your handling code here:
        displayTA.setText("");
        searchappliance.setSelectedIndex(0);   // reset dropdown
    }//GEN-LAST:event_removeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ApplianceListForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel applianceLBL;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel backLBL;
    private javax.swing.JLabel backgroundLBL;
    private javax.swing.JPanel backgroundPL;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton removeBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JComboBox<String> searchappliance;
    // End of variables declaration//GEN-END:variables

    private Object subString(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
