/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Odmaa;

import power.wise.app.PowerWiseGUI;
/**
 *
 * @author apple
 */
public class ApplianceGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ApplianceGUI.class.getName());

    /**
     * Creates new form ApplaiceGUI
     */
    public ApplianceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        applianceLBL = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        mainMenuBTN = new javax.swing.JButton();
        applianceListBTN = new javax.swing.JButton();
        iconLBL = new javax.swing.JLabel();
        backgroundLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(26, 101, 26));

        applianceLBL.setBackground(new java.awt.Color(26, 101, 26));
        applianceLBL.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        applianceLBL.setForeground(new java.awt.Color(255, 255, 255));
        applianceLBL.setText("Power Wise - Appliance");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(applianceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(applianceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.setToolTipText("");
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenuBTN.setBackground(new java.awt.Color(26, 101, 26));
        mainMenuBTN.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        mainMenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });
        mainPanel.add(mainMenuBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 163, 62));

        applianceListBTN.setBackground(new java.awt.Color(26, 101, 26));
        applianceListBTN.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        applianceListBTN.setForeground(new java.awt.Color(255, 255, 255));
        applianceListBTN.setText("Appliance List");
        applianceListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applianceListBTNActionPerformed(evt);
            }
        });
        mainPanel.add(applianceListBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 62));

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/electric-appliance.png"))); // NOI18N
        iconLBL.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mainPanel.add(iconLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));

        backgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/appliancebackground.jpg"))); // NOI18N
        backgroundLBL.setText("jLabel1");
        mainPanel.add(backgroundLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 900, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 329, Short.MAX_VALUE))
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        new PowerWiseGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    private void applianceListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applianceListBTNActionPerformed
        // TODO add your handling code here:
        new ApplianceListForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applianceListBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ApplianceGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applianceLBL;
    private javax.swing.JButton applianceListBTN;
    private javax.swing.JLabel backgroundLBL;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
